version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehiclemarket
      SPRING_DATASOURCE_USERNAME: userclient
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vehiclemarket
      POSTGRES_USER: userclient
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend:
